// src/package/luzon.js
const luzon = [
  // BATANES
  {
    id: "LZ-1",
    destination: "Batanes",
    set: "A",
    duration: "4D3N",
    packageName: "Batanes 4D3N Set A",
    accommodation: "Amboy Hometel",
    accommodationImage: "/luzon/accommodation/Amboy Hometel.webp",
    spotImages: ["/luzon/spots/Amboy Hometel.jpg", "/luzon/Tinyan Viewpoint.jpg"],
    foodImage: "/luzon/dining/Hiro's Cafe.jpg",
    inclusions: [
      "4D3N accommodation at Amboy Hometel",
      "North, South, and Sabtang tours",
      "Local meals and transport",
      "Entrance and environmental fees",
    ],
    expenses: { accommodation: 5000, food: 3500, activities: 4000, misc: 1000 },
    estimatedCost: "₱11,000–₱15,000",
    region: "Luzon",
    travelType: ["Nature", "Adventure"],
  },

  // BANAUE – SAGADA
  {
    id: "LZ-2",
    destination: "Banaue–Sagada",
    set: "A",
    duration: "4D3N",
    packageName: "Banaue–Sagada 4D3N Set A",
    accommodation: "Banaue View Inn & Sagada Heritage Village",
    accommodationImage: "/luzon/accomodation/Banaue View Inn.jpg",
    spotImages: [
      "/luzon/spots/Banaue Viewpoint.jpg",
      "/luzon/spots/banaue Museum.jpg",
      "/luzon/spots/banaue local weaving shop.webp",
    ],
    foodImage: "/luzon/dining/Batad Pension & Restaurant.jpg",
    inclusions: [
      "Banaue and Sagada tours",
      "Trekking to Tappiya Falls & Batad",
      "Visit Hanging Coffins, Sumaguing Cave",
      "Meals and local transport",
    ],
    expenses: { accommodation: 4500, food: 3000, activities: 4000, misc: 800 },
    estimatedCost: "₱12,000–₱14,000",
    region: "Luzon",
    travelType: ["Nature", "Cultural"],
  },

  {
    id: "LZ-3",
    destination: "Banaue–Sagada",
    set: "B",
    duration: "4D3N",
    packageName: "Banaue–Sagada 4D3N Set B",
    accommodation: "Coffee Heritage House / Masferre Inn",
    accommodationImage: "/luzon/accommodation/sagad Coffee Heritage House.webp",
    spotImages: ["/luzon/spots/Banaue Viewpoint.jpg", "/luzon/spots/banaue Museum.jpg"],
    foodImage: "/luzon/dining/Yoghurt House.webp",
    inclusions: [
      "Light trekking and cultural tours",
      "Coffee farm + pottery workshop",
      "Café and food trip stops",
      "Souvenir and weaving shop visits",
    ],
    expenses: { accommodation: 5500, food: 3500, activities: 3500, misc: 1000 },
    estimatedCost: "₱10,000–₱13,000",
    region: "Luzon",
    travelType: ["Nature", "Cultural"],
  },

  {
    id: "LZ-4",
    destination: "Banaue–Sagada",
    set: "A",
    duration: "3D2N",
    packageName: "Banaue–Sagada 3D2N Set A",
    accommodation: "Banaue View Inn",
    accommodationImage: "/luzon/accommodation/Banaue View Inn.jpg",
    spotImages: ["/luzon/Banaue Viewpoint.jpg", "/luzon/banaue Museum.jpg"],
    foodImage: "/luzon/dining/Sagada Brew.webp",
    inclusions: ["3D2N stay", "Batad and Tappiya highlights", "Transport and meals"],
    expenses: { accommodation: 3300, food: 2400, activities: 2800, misc: 700 },
    estimatedCost: "₱9,000–₱11,000",
    region: "Luzon",
    travelType: ["Nature"],
  },

  {
    id: "LZ-5",
    destination: "Banaue–Sagada",
    set: "A",
    duration: "1 Day",
    packageName: "Banaue–Sagada 1 Day Tour Set A",
    accommodation: "N/A (Day Tour)",
    accommodationImage: "/luzon/Tappiya Falls.webp",
    spotImages: ["/luzon/spots/banaue Museum.jpg", "/luzon/spots/Banaue Viewpoint.jpg"],
    foodImage: "/luzon/dining/Yoghurt House.webp",
    inclusions: ["Day trip highlights (viewpoints & museum)", "Lunch and transport"],
    expenses: { accommodation: 0, food: 800, activities: 1200, misc: 300 },
    estimatedCost: "₱3,500–₱5,000",
    region: "Luzon",
    travelType: ["Cultural"],
  },

  // BAGUIO
  {
    id: "LZ-6",
    destination: "Baguio",
    set: "A",
    duration: "4D3N",
    packageName: "Baguio 4D3N Set A",
    accommodation: "Hotel Veniz / 456 Hotel",
    accommodationImage: "/luzon/accommodation/Hotel Veni.jpg",
    spotImages: [
      "/luzon/spots/BenCab Museu.jpg",
      "/luzon/spots/Baguio Public Market.jpg",
      "/luzon/spots/Botanical Garden.jpg",
    ],
    foodImage: "/luzon/dining/arca's yard cafe.jpg",
    inclusions: [
      "4D3N accommodation",
      "City tour and museum visits",
      "Park entries and local dining",
      "Souvenir shopping assistance",
    ],
    expenses: { accommodation: 4000, food: 2500, activities: 3000, misc: 800 },
    estimatedCost: "₱9,000–₱10,500",
    region: "Luzon",
    travelType: ["City Tour", "Cultural"],
  },

  {
    id: "LZ-7",
    destination: "Baguio",
    set: "B",
    duration: "4D3N",
    packageName: "Baguio 4D3N Set B",
    accommodation: "The Forest Lodge at Camp John Hay",
    accommodationImage: "/luzon/accommodation/The Forest Lodge.jpg",
    spotImages: [
      "/luzon/spots/Mines View Par.png",
      "/luzon/spots/Baguio Public Market.jpg",
      "/luzon/spots/BenCab Museu.jpg",
    ],
    foodImage: "/luzon/dining/Cafe Yagam.jpg",
    inclusions: [
      "Café hopping + scenic walks",
      "Art stops and nature relax spots",
      "Shopping at Good Shepherd & Market",
      "Dining at popular food hubs",
    ],
    expenses: { accommodation: 5500, food: 3500, activities: 3000, misc: 1000 },
    estimatedCost: "₱10,000–₱12,000",
    region: "Luzon",
    travelType: ["City Tour", "Leisure"],
  },

  {
    id: "LZ-8",
    destination: "Baguio",
    set: "A",
    duration: "3D2N",
    packageName: "Baguio 3D2N Set A",
    accommodation: "Hotel Veniz",
    accommodationImage: "/luzon/accommodation/Hotel Veni.jpg",
    spotImages: [
      "/luzon/spots/Botanical Garden.jpg",
      "/luzon/spots/Baguio Public Market.jpg",
      "/luzon/spots/BenCab Museu.jpg",
    ],
    foodImage: "/luzon/dining/Hill Station.jpg",
    inclusions: ["3D2N city highlights", "Museums and parks", "Local dining"],
    expenses: { accommodation: 3200, food: 2200, activities: 2600, misc: 700 },
    estimatedCost: "₱7,500–₱9,000",
    region: "Luzon",
    travelType: ["City Tour"],
  },

  {
    id: "LZ-9",
    destination: "Baguio",
    set: "B",
    duration: "3D2N",
    packageName: "Baguio 3D2N Set B",
    accommodation: "Venus Parkview / Forest Lodge",
    accommodationImage: "/luzon/accommodation/The Forest Lodge.jpg",
    spotImages: ["/luzon/spots/The Mansion.jpg", "/luzon/spots/Mines View Par.png"],
    foodImage: "/luzon/dining/Oh My Gulay.jpg",
    inclusions: ["Café & art trail", "Nature walks and light activities", "Shopping at Baguio Market"],
    expenses: { accommodation: 4200, food: 2800, activities: 2400, misc: 800 },
    estimatedCost: "₱8,000–₱9,500",
    region: "Luzon",
    travelType: ["City Tour", "Leisure"],
  },

  {
    id: "LZ-10",
    destination: "Baguio",
    set: "A",
    duration: "2D1N",
    packageName: "Baguio 2D1N Set A",
    accommodation: "Budget Hotel / Guesthouse",
    accommodationImage: "/luzon/accommodation/456 Hotel.jpg",
    spotImages: ["/luzon/spots/Wright Park.JPG", "/luzon/spots/Baguio Public Market.jpg"],
    foodImage: "/luzon/dining/Choco-late de Batirol.jpg",
    inclusions: ["Quick city highlights", "Park visits and market stop"],
    expenses: { accommodation: 1800, food: 1200, activities: 1500, misc: 500 },
    estimatedCost: "₱5,000–₱6,500",
    region: "Luzon",
    travelType: ["City Tour"],
  },

  // TAGAYTAY
  {
    id: "LZ-11",
    destination: "Tagaytay",
    set: "A",
    duration: "4D3N",
    packageName: "Tagaytay 4D3N Set A",
    accommodation: "Nurture Wellness Village",
    accommodationImage: "/luzon/accommodation/Venus Parkview.jpeg",
    spotImages: ["/luzon/spots/Twin Lakes Promenad.jpg", "/luzon/spots/Sky Ranch tagaytay.jpg"],
    foodImage: "/luzon/dining/Hill Station.jpg",
    inclusions: [
      "Accommodation with wellness experience",
      "Garden tours & spa option",
      "Scenic café hopping",
      "Local souvenir shopping",
    ],
    expenses: { accommodation: 9000, food: 4500, activities: 3500, misc: 1000 },
    estimatedCost: "₱15,000–₱28,000",
    region: "Luzon",
    travelType: ["Leisure", "Nature"],
  },

  // VIGAN
  {
    id: "LZ-12",
    destination: "Vigan",
    set: "A",
    duration: "4D3N",
    packageName: "Vigan 4D3N Set A",
    accommodation: "Hotel Luna / Ciudad Fernandina",
    accommodationImage: "/luzon/accommodation/Hotel Luna.jpg",
    spotImages: ["/luzon/spots/Paoay Church.jpg", "/luzon/spots/Hidden Garden.jpg", "/luzon/spots/Laoag Sand Dunes.jpg"],
    foodImage: "/luzon/dining/Cafe Leona.jpg",
    inclusions: ["Heritage walks, Calle Crisologo", "Pagudpud loop (optional), Paoay & Laoag day trip", "Accommodation and meals"],
    expenses: { accommodation: 6000, food: 3500, activities: 4000, misc: 1000 },
    estimatedCost: "₱12,000–₱16,000",
    region: "Luzon",
    travelType: ["Cultural", "City Tour"],
  },

  {
    id: "LZ-13",
    destination: "Vigan",
    set: "A",
    duration: "3D2N",
    packageName: "Vigan 3D2N Set A",
    accommodation: "Hotel Luna / Midrange Inn",
    accommodationImage: "/luzon/accommodation/Hotel Luna.jpg",
    spotImages: ["/luzon/spots/Calle Crisologo.jpg", "/luzon/spots/Hidden Garden.jpg", "/luzon/spots/Paoay Church.jpg"],
    foodImage: "/luzon/dining/Cafe Leona.jpg",
    inclusions: ["3D2N heritage highlights", "Calle Crisologo, Syquia Mansion, Baluarte", "Meals and guide"],
    expenses: { accommodation: 3800, food: 2200, activities: 2600, misc: 700 },
    estimatedCost: "₱9,000–₱11,000",
    region: "Luzon",
    travelType: ["Cultural", "City Tour"],
  },
];

export default luzon;
