// src/package/mindanao.js
const mindanao = [
  // DAVAO
  {
    id: "MD-1",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "4D3N",
    packageName: "Davao 4D3N Set A",
    accommodation: "Red Planet Davao",
    accommodationImage: "/mindanao/accommodation/Red Planet.webp",
    spotImages: ["/mindanao/spots/Eden Nature Park.jpg", "/mindanao/spots/Crocodile Park.JPG", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Roxas Night Market.jpg",
    inclusions: ["City tour + Eden Nature Park", "Night market food trip", "Meals + transport"],
    expenses: { accommodation: 5000, food: 3500, activities: 4000, misc: 1000 },
    estimatedCost: "₱14,000–₱18,000",
  },
  {
    id: "MD-2",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "B",
    duration: "4D3N",
    packageName: "Davao 4D3N Set B",
    accommodation: "Seda Abreeza Hotel",
    accommodationImage: "/mindanao/accommodation/Seda Abreeza.jpg",
    spotImages: ["/mindanao/spots/Crocodile Park.JPG", "/mindanao/spots/Eden Nature Park.jpg", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Blugre Caf.jpg",
    inclusions: ["Luxury city stay", "Samal Island day trip", "Meals + transfers"],
    expenses: { accommodation: 8000, food: 4500, activities: 5000, misc: 1200 },
    estimatedCost: "₱18,000–₱24,000",
  },
  {
    id: "MD-3",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "3D2N",
    packageName: "Davao 3D2N Set A",
    accommodation: "Red Planet Davao",
    accommodationImage: "/mindanao/accommodation/Red Planet.webp",
    spotImages: ["/mindanao/spots/People's Park.jpg", "/mindanao/spots/Crocodile Park.JPG", "/mindanao/spots/Eden Nature Park.jpg"],
    foodImage: "/mindanao/dining/Blugre Caf.jpg",
    inclusions: ["City essentials tour", "Transport + meals"],
    expenses: { accommodation: 3500, food: 2200, activities: 3000, misc: 500 },
    estimatedCost: "₱9,000–₱12,000",
  },
  {
    id: "MD-4",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "B",
    duration: "3D2N",
    packageName: "Davao 3D2N Set B",
    accommodation: "Seda Abreeza Hotel",
    accommodationImage: "/mindanao/accommodation/Seda Abreeza.jpg",
    spotImages: ["/mindanao/spots/Samal Island.jpg", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Roxas Night Market.jpg",
    inclusions: ["Island + city enjoyment"],
    expenses: { accommodation: 5500, food: 3000, activities: 3500, misc: 600 },
    estimatedCost: "₱11,000–₱15,000",
  },
  {
    id: "MD-5",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "2D1N",
    packageName: "Davao 2D1N Set A",
    accommodation: "Red Planet Davao",
    accommodationImage: "/mindanao/accommodation/Red Planet.webp",
    spotImages: ["/mindanao/spots/Crocodile Park.JPG", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Roxas Night Market.jpg",
    inclusions: ["City mini tour"],
    expenses: { accommodation: 2000, food: 1300, activities: 2000, misc: 300 },
    estimatedCost: "₱6,000–₱8,000",
  },
  {
    id: "MD-6",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "A",
    duration: "1 Day",
    packageName: "Davao Day Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/Crocodile Park.JPG", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Blugre Caf.jpg",
    inclusions: ["City day tour"],
    expenses: { accommodation: 0, food: 500, activities: 800, misc: 200 },
    estimatedCost: "₱1,500–₱2,500",
  },
  {
    id: "MD-7",
    destination: "Davao",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "B",
    duration: "1 Day",
    packageName: "Samal Escape Day Tour Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/Samal Island.jpg", "/mindanao/spots/People's Park.jpg"],
    foodImage: "/mindanao/dining/Blugre Caf.jpg",
    inclusions: ["Island leisure + lunch"],
    expenses: { accommodation: 0, food: 900, activities: 1500, misc: 300 },
    estimatedCost: "₱3,000–₱4,000",
  },

  // SIARGAO
  {
    id: "MD-8",
    destination: "Siargao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "4D3N",
    packageName: "Siargao 4D3N Set A",
    accommodation: "Hiraya Siargao Hostel",
    accommodationImage: "/mindanao/accommodation/Harana Surf.jpg",
    spotImages: ["/mindanao/spots/Cloud 9 sunset.jpg", "/mindanao/spots/Sugba Lagoon.jpg", "/mindanao/spots/daku.jpg", "/mindanao/spots/Guyam.jpg"],
    foodImage: "/mindanao/dining/Kermit Siargao.jpg",
    inclusions: ["Surf session", "Island hopping (Daku + Guyam + Naked)", "Sugba Lagoon", "Meals + transport"],
    expenses: { accommodation: 4500, food: 3500, activities: 5500, misc: 1000 },
    estimatedCost: "₱14,000–₱18,000",
  },
  {
    id: "MD-9",
    destination: "Siargao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "B",
    duration: "4D3N",
    packageName: "Siargao 4D3N Set B",
    accommodation: "Bravo Beach Resort",
    accommodationImage: "/mindanao/accommodation/Bravo Beach Resort.jpg",
    spotImages: ["/mindanao/spots/Sugba Lagoon.jpg", "/mindanao/spots/Cloud 9 sunset.jpg", "/mindanao/spots/daku.jpg", "/mindanao/spots/Guyam.jpg"],
    foodImage: "/mindanao/dining/Luz Kinilaw.jpg",
    inclusions: ["Luxury beachfront stay", "Sohoton Cove Tour", "Surfing + lagoon experience"],
    expenses: { accommodation: 8500, food: 4500, activities: 6000, misc: 1200 },
    estimatedCost: "₱20,000–₱27,000",
  },
  {
    id: "MD-10",
    destination: "Siargao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "3D2N",
    packageName: "Siargao 3D2N Set A",
    accommodation: "Hiraya Siargao Hostel",
    accommodationImage: "/mindanao/accommodation/Harana Surf.jpg",
    spotImages: ["/mindanao/spots/daku.jpg", "/mindanao/spots/Sugba Lagoon.jpg", "/mindanao/spots/Cloud 9 sunset.jpg"],
    foodImage: "/mindanao/dining/Luz Kinilaw.jpg",
    inclusions: ["Budget surf trip", "Island hopping lite"],
    expenses: { accommodation: 3000, food: 2200, activities: 4000, misc: 600 },
    estimatedCost: "₱9,500–₱12,500",
  },
  {
    id: "MD-11",
    destination: "Siargao",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "B",
    duration: "3D2N",
    packageName: "Siargao 3D2N Set B",
    accommodation: "Bravo Beach Resort",
    accommodationImage: "/mindanao/accommodation/Bravo Beach Resort.jpg",
    spotImages: ["/mindanao/spots/Sugba Lagoon.jpg", "/mindanao/spots/Cloud 9 sunset.jpg"],
    foodImage: "/mindanao/dining/Shaka Caf.webp",
    inclusions: ["Surf + scenic lagoon trip"],
    expenses: { accommodation: 6000, food: 3000, activities: 3500, misc: 700 },
    estimatedCost: "₱12,500–₱16,000",
  },

  // CAMIGUIN
  {
    id: "MD-12",
    destination: "Camiguin",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "4D3N",
    packageName: "Camiguin 4D3N Set A",
    accommodation: "Pabua’s Cottages",
    accommodationImage: "/mindanao/accommodation/Paras Beach Resort.jpg",
    spotImages: ["/mindanao/spots/White Island.jpg", "/mindanao/spots/Mantigue Island.jpg", "/mindanao/spots/Ardent Hot Spring.jpg"],
    foodImage: "/mindanao/dining/Guerrera Restaurant.jpg",
    inclusions: ["White Island & Mantigue Island", "Countryside + hot springs", "Meals + transport"],
    expenses: { accommodation: 4500, food: 3000, activities: 4500, misc: 800 },
    estimatedCost: "₱13,000–₱18,000",
  },
  {
    id: "MD-13",
    destination: "Camiguin",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "B",
    duration: "4D3N",
    packageName: "Camiguin 4D3N Set B",
    accommodation: "Paras Beach Resort",
    accommodationImage: "/mindanao/accommodation/Paras Beach Resort.webp",
    spotImages: ["/mindanao/spots/Mantigue Island.jpg", "/mindanao/spots/White Island.jpg", "/mindanao/spots/Ardent Hot Spring.jpg"],
    foodImage: "/mindanao/dining/Luna Ristorante.webp",
    inclusions: ["Beachfront luxury stay", "White Island + diving", "Meals + transfers"],
    expenses: { accommodation: 7000, food: 4000, activities: 5000, misc: 1200 },
    estimatedCost: "₱18,000–₱24,000",
  },
  {
    id: "MD-14",
    destination: "Camiguin",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "A",
    duration: "1 Day",
    packageName: "Camiguin Day Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/White Island.jpg", "/mindanao/spots/Ardent Hot Spring.jpg"],
    foodImage: "/mindanao/dining/Luna Ristorante.webp",
    inclusions: ["Heritage & hot spring day trip"],
    expenses: { accommodation: 0, food: 500, activities: 800, misc: 200 },
    estimatedCost: "₱2,000–₱3,000",
  },
  {
    id: "MD-15",
    destination: "Camiguin",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "B",
    duration: "1 Day",
    packageName: "Camiguin Island Leisure Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/White Island.jpg"],
    foodImage: "/mindanao/dining/Luna Ristorante.webp",
    inclusions: ["Beach trip + lunch"],
    expenses: { accommodation: 0, food: 800, activities: 1200, misc: 300 },
    estimatedCost: "₱3,000–₱4,500",
  },

  // BUKIDNON
  {
    id: "MD-16",
    destination: "Bukidnon",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "4D3N",
    packageName: "Bukidnon 4D3N Set A",
    accommodation: "Dahilayan Forest Park Hotel",
    accommodationImage: "/mindanao/accommodation/Dahilayan Forest Park Resort.jpg",
    spotImages: [
      "/mindanao/spots/Camp Phillips.JPG",
      "/mindanao/spots/Dahilayan Adventure Park.jpg",
      "/mindanao/spots/Kaamulan Grounds.jpg",
      "/mindanao/spots/monasterytransfiguration.jpg",
      "/mindanao/spots/Monastery of Transfiguration.jpg",
    ],
    foodImage: "/mindanao/dining/Cowboys's Grill.jpg",
    inclusions: ["Adventure park rides", "Mountain viewpoints", "Meals + transfers"],
    expenses: { accommodation: 5000, food: 3000, activities: 4500, misc: 800 },
    estimatedCost: "₱13,000–₱18,000",
  },
  {
    id: "MD-17",
    destination: "Bukidnon",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "3D2N",
    packageName: "Bukidnon 3D2N Set A",
    accommodation: "Dahilayan Forest Park Hotel",
    accommodationImage: "/mindanao/accommodation/Dahilayan Forest Park Resort.jpg",
    spotImages: ["/mindanao/spots/monasterytransfiguration.jpg", "/mindanao/spots/Dahilayan Adventure Park.jpg", "/mindanao/spots/Kaamulan Grounds.jpg"],
    foodImage: "/mindanao/dining/Del Monte Clubhouse.jpg",
    inclusions: ["Thrill rides + scenic farms"],
    expenses: { accommodation: 3500, food: 2000, activities: 3500, misc: 500 },
    estimatedCost: "₱9,500–₱13,000",
  },
  {
    id: "MD-18",
    destination: "Bukidnon",
    region: "Mindanao",
    travelType: "Multi-day",
    set: "A",
    duration: "2D1N",
    packageName: "Bukidnon 2D1N Set A",
    accommodation: "Forest Lodge",
    accommodationImage: "/mindanao/accommodation/Dahilayan Forest Park Resort.jpg",
    spotImages: ["/mindanao/spots/Dahilayan Adventure Park.jpg", "/mindanao/spots/Kaamulan Grounds.jpg"],
    foodImage: "/mindanao/dining/Cowboys's Grill.jpg",
    inclusions: ["Nature + chill tour"],
    expenses: { accommodation: 1800, food: 1200, activities: 2000, misc: 300 },
    estimatedCost: "₱6,500–₱8,500",
  },
  {
    id: "MD-19",
    destination: "Bukidnon",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "A",
    duration: "1 Day",
    packageName: "Bukidnon Day Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/Kaamulan Grounds.jpg", "/mindanao/spots/Dahilayan Adventure Park.jpg"],
    foodImage: "/mindanao/dining/bukidnonn.jpg",
    inclusions: ["Thrills + quick site visit"],
    expenses: { accommodation: 0, food: 500, activities: 1000, misc: 200 },
    estimatedCost: "₱1,700–₱2,700",
  },
  {
    id: "MD-20",
    destination: "Bukidnon",
    region: "Mindanao",
    travelType: "Day Tour",
    set: "B",
    duration: "1 Day",
    packageName: "Bukidnon Adventure Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/mindanao/spots/Dahilayan Adventure Park.jpg"],
    foodImage: "/mindanao/dining/bukidnonn.jpg",
    inclusions: ["Full adventure park access"],
    expenses: { accommodation: 0, food: 800, activities: 1800, misc: 300 },
    estimatedCost: "₱3,000–₱4,500",
  },
];

export default mindanao;
