// src/package/visayas.js
const visayas = [
  // CEBU
  {
    id: "VS-1",
    region: "Visayas",
    destination: "Cebu",
    set: "A",
    duration: "4D3N",
    packageName: "Cebu 4D3N Set A",
    accommodation: "Quest Hotel / Southpole Central",
    accommodationImage: "/visayas/accommodation/Quest Hotel.jpg",
    spotImages: [
      "/visayas/spots/Tumalog Falls.jpg",
      "/visayas/spots/Fort San Pedro.jpg",
      "/visayas/spots/Magellan's Cross.jpg",
    ],
    foodImage: "/visayas/dining/House of Lechon.jpg",
    inclusions: ["4D3N accommodation", "City tour + Oslob + Kawasan Falls + Moalboal", "Canyoneering + snorkeling fees", "Meals and transport"],
    expenses: { accommodation: 6000, food: 3500, activities: 5500, misc: 1000 },
    estimatedCost: "₱15,000–₱20,000",
    travelType: ["Beach", "Adventure"],
  },
  {
    id: "VS-2",
    region: "Visayas",
    destination: "Cebu",
    set: "B",
    duration: "4D3N",
    packageName: "Cebu 4D3N Set B",
    accommodation: "Crimson Resort / Movenpick",
    accommodationImage: "/visayas/accommodation/Crimson Resort.jpg",
    spotImages: ["/visayas/spots/Gilutongan.jpg", "/visayas/spots/Caohangan Islands.jpg", "/visayas/spots/Ayala Cebu.jpg"],
    foodImage: "/visayas/dining/Ibiza Beach Club.jpg",
    inclusions: ["Island hopping", "Beach resort leisure", "City + scenic food trip", "Meals and transport"],
    expenses: { accommodation: 8000, food: 4000, activities: 5000, misc: 1000 },
    estimatedCost: "₱18,000–₱25,000",
    travelType: ["Beach", "Leisure"],
  },
  {
    id: "VS-3",
    region: "Visayas",
    destination: "Cebu",
    set: "A",
    duration: "3D2N",
    packageName: "Cebu 3D2N Set A",
    accommodation: "Southpole Central",
    accommodationImage: "/visayas/accommodation/Southpole Central.jpg",
    spotImages: ["/visayas/spots/Tumalog Falls.jpg", "/visayas/spots/Snorkeling in Moalboal.jpg", "/visayas/spots/Whale Shark watching.jpg"],
    foodImage: "/visayas/dining/Rico's Lechon.jpg",
    inclusions: ["Oslob whale shark", "Tumalog falls", "Moalboal snorkeling"],
    expenses: { accommodation: 3500, food: 2000, activities: 4000, misc: 500 },
    estimatedCost: "₱12,000–₱16,000",
    travelType: ["Beach", "Adventure"],
  },
  {
    id: "VS-4",
    region: "Visayas",
    destination: "Cebu",
    set: "B",
    duration: "3D2N",
    packageName: "Cebu 3D2N Set B",
    accommodation: "Crimson Resort",
    accommodationImage: "/visayas/accommodation/Crimson Resort.jpg",
    spotImages: ["/visayas/spots/Whale Shark watching.jpg", "/visayas/spots/Sirao Flower Garden.jpg", "/visayas/spots/Ayala Cebu.jpg"],
    foodImage: "/visayas/dining/Rico's Lechon.jpg",
    inclusions: ["Island hopping", "City shopping + leisure", "Transport"],
    expenses: { accommodation: 5500, food: 2500, activities: 3000, misc: 500 },
    estimatedCost: "₱13,000–₱17,000",
    travelType: ["Beach", "Leisure"],
  },
  {
    id: "VS-5",
    region: "Visayas",
    destination: "Cebu",
    set: "A",
    duration: "2D1N",
    packageName: "Cebu 2D1N Set A",
    accommodation: "Southpole Central",
    accommodationImage: "/visayas/accommodation/Southpole Central.jpg",
    spotImages: ["/visayas/spots/Fort San Pedro.jpg", "/visayas/spots/Magellan's Cross.jpg"],
    foodImage: "/visayas/dining/House of Lechon.jpg",
    inclusions: ["City tour", "Whale shark viewing"],
    expenses: { accommodation: 2000, food: 1500, activities: 3000, misc: 500 },
    estimatedCost: "₱8,000–₱10,000",
    travelType: ["City Tour", "Beach"],
  },
  {
    id: "VS-6",
    region: "Visayas",
    destination: "Cebu",
    set: "A",
    duration: "1 Day",
    packageName: "Cebu City Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Magellan's Cross.jpg", "/visayas/spots/Fort San Pedro.jpg"],
    foodImage: "/visayas/dining/Rico's Lechon.jpg",
    inclusions: ["City heritage trip", "Transport & lunch"],
    expenses: { accommodation: 0, food: 800, activities: 1000, misc: 200 },
    estimatedCost: "₱2,000–₱3,000",
    travelType: ["City Tour"],
  },

  // BOHOL
  {
    id: "VS-7",
    region: "Visayas",
    destination: "Bohol",
    set: "A",
    duration: "4D3N",
    packageName: "Bohol 4D3N Set A",
    accommodation: "Alona Beach Resort",
    accommodationImage: "/visayas/accommodation/alona.jpg",
    spotImages: ["/visayas/spots/Loboc River.jpg", "/visayas/spots/tarsier in bohol.jpg", "/visayas/spots/Balicasag.jpg", "/visayas/spots/Virgin Island.jpg"],
    foodImage: "/visayas/dining/foodalona.webp",
    inclusions: ["Countryside tour", "Island hopping", "Meals & transfers"],
    expenses: { accommodation: 6000, food: 3000, activities: 5000, misc: 1000 },
    estimatedCost: "₱15,000–₱20,000",
    travelType: ["Beach", "Nature"],
  },
  {
    id: "VS-8",
    region: "Visayas",
    destination: "Bohol",
    set: "A",
    duration: "1 Day",
    packageName: "Bohol Day Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Chocolate Hills.jpg", "/visayas/spots/Loboc River.jpg"],
    foodImage: "/visayas/dining/foodalona.webp",
    inclusions: ["Countryside day trip", "River cruise buffet"],
    expenses: { accommodation: 0, food: 700, activities: 1000, misc: 200 },
    estimatedCost: "₱2,500–₱3,500",
    travelType: ["Nature", "Cultural"],
  },
  {
    id: "VS-9",
    region: "Visayas",
    destination: "Bohol",
    set: "B",
    duration: "1 Day",
    packageName: "Island Hopping Bohol Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Balicasag.jpg", "/visayas/spots/Virgin Island.jpg"],
    foodImage: "/visayas/dining/foodalona.webp",
    inclusions: ["Island hopping", "Seafood lunch"],
    expenses: { accommodation: 0, food: 900, activities: 1400, misc: 300 },
    estimatedCost: "₱3,500–₱5,000",
    travelType: ["Beach"],
  },

  // BORACAY (AKLAN)
  {
    id: "VS-10",
    region: "Visayas",
    destination: "Boracay",
    set: "A",
    duration: "4D3N",
    packageName: "Boracay 4D3N Set A",
    accommodation: "La Carmela de Boracay",
    accommodationImage: "/visayas/accommodation/lacarmela.jpg",
    spotImages: ["/visayas/spots/Crystal Cove.jpg", "/visayas/spots/Crocodile Island.jpg", "/visayas/spots/Puka Beach.jpg"],
    foodImage: "/visayas/dining/Food Trip bora.jpg",
    inclusions: ["4D3N budget hotel", "White Beach + D'Mall + Bulabog", "Sunset watching"],
    expenses: { accommodation: 5500, food: 3500, activities: 4000, misc: 1000 },
    estimatedCost: "₱14,000–₱18,000",
    travelType: ["Beach", "Leisure"],
  },
  {
    id: "VS-11",
    region: "Visayas",
    destination: "Boracay",
    set: "B",
    duration: "4D3N",
    packageName: "Boracay 4D3N Set B",
    accommodation: "Henann Prime Beach Resort",
    accommodationImage: "/visayas/accommodation/henann.jpg",
    spotImages: ["/visayas/spots/Puka Beach.jpg", "/visayas/spots/Crystal Cove.jpg", "/visayas/spots/Crocodile Island.jpg"],
    foodImage: "/visayas/dining/Food Trip bora.jpg",
    inclusions: ["Luxury beachfront hotel", "Water sports (parasailing, snorkeling)", "Island BBQ feast"],
    expenses: { accommodation: 9000, food: 4500, activities: 5500, misc: 1200 },
    estimatedCost: "₱21,000–₱28,000",
    travelType: ["Beach", "Luxury"],
  },
  {
    id: "VS-12",
    region: "Visayas",
    destination: "Boracay",
    set: "A",
    duration: "1 Day",
    packageName: "Boracay Day Trip Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Crystal Cove.jpg", "/visayas/spots/Crocodile Island.jpg"],
    foodImage: "/visayas/dining/Food Trip bora.jpg",
    inclusions: ["White Beach leisure", "Lunch included"],
    expenses: { accommodation: 0, food: 700, activities: 800, misc: 200 },
    estimatedCost: "₱1,700–₱2,700",
    travelType: ["Beach", "Day Trip"],
  },
  {
    id: "VS-13",
    region: "Visayas",
    destination: "Boracay",
    set: "B",
    duration: "1 Day",
    packageName: "Boracay Island Hopping Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Puka Beach.jpg", "/visayas/spots/Crystal Cove.jpg"],
    foodImage: "/visayas/dining/Food Trip bora.jpg",
    inclusions: ["Island hopping tour", "Seafood lunch"],
    expenses: { accommodation: 0, food: 1100, activities: 1400, misc: 300 },
    estimatedCost: "₱3,000–₱4,500",
    travelType: ["Beach"],
  },

  // SIQUIJOR
  {
    id: "VS-14",
    region: "Visayas",
    destination: "Siquijor",
    set: "A",
    duration: "4D3N",
    packageName: "Siquijor 4D3N Set A",
    accommodation: "JJ’s Backpackers Village",
    accommodationImage: "/visayas/accommodation/jjs.jpg",
    spotImages: ["/visayas/spots/Cabugahay Falls.jpg", "/visayas/spots/Salagdoong Beach.jpg", "/visayas/spots/San Juan Beach.jpg"],
    foodImage: "/visayas/dining/food.jpg",
    inclusions: ["Waterfalls & beach tour", "Heritage and mystic sites", "Meals + transfers"],
    expenses: { accommodation: 4500, food: 2500, activities: 3500, misc: 600 },
    estimatedCost: "₱11,000–₱14,000",
    travelType: ["Beach", "Nature"],
  },
  {
    id: "VS-15",
    region: "Visayas",
    destination: "Siquijor",
    set: "B",
    duration: "4D3N",
    packageName: "Siquijor 4D3N Set B",
    accommodation: "Coco Grove Beach Resort",
    accommodationImage: "/visayas/accommodation/coco.jpg",
    spotImages: ["/visayas/spots/Salagdoong Beach.jpg", "/visayas/spots/Cabugahay Falls.jpg", "/visayas/spots/San Juan Beach.jpg"],
    foodImage: "/visayas/dining/foods.jpg",
    inclusions: ["Luxury beach stay", "Marine sanctuary visit", "Meals + spa (optional)"],
    expenses: { accommodation: 8000, food: 3500, activities: 4000, misc: 900 },
    estimatedCost: "₱16,000–₱20,000",
    travelType: ["Beach", "Leisure"],
  },
  {
    id: "VS-16",
    region: "Visayas",
    destination: "Siquijor",
    set: "A",
    duration: "3D2N",
    packageName: "Siquijor 3D2N Set A",
    accommodation: "JJ’s Backpackers Village",
    accommodationImage: "/visayas/accommodation/jjs.jpg",
    spotImages: ["/visayas/spots/Cabugahay Falls.jpg", "/visayas/spots/Salagdoong Beach.jpg", "/visayas/spots/San Juan Beach.jpg"],
    foodImage: "/visayas/dining/foodss.jpg",
    inclusions: ["Quick waterfalls + heritage trip", "Lunch + transfers"],
    expenses: { accommodation: 3000, food: 2000, activities: 2500, misc: 400 },
    estimatedCost: "₱8,000–₱10,000",
    travelType: ["Beach", "Nature"],
  },
  {
    id: "VS-17",
    region: "Visayas",
    destination: "Siquijor",
    set: "B",
    duration: "3D2N",
    packageName: "Siquijor 3D2N Set B",
    accommodation: "Coco Grove Beach Resort",
    accommodationImage: "/visayas/accommodation/coco.jpg",
    spotImages: ["/visayas/spots/Salagdoong Beach.jpg", "/visayas/spots/Cabugahay Falls.jpg", "/visayas/spots/San Juan Beach.jpg"],
    foodImage: "/visayas/dining/hut food.jpg",
    inclusions: ["Beach leisure", "Marine sanctuary tour"],
    expenses: { accommodation: 5000, food: 2500, activities: 3000, misc: 600 },
    estimatedCost: "₱10,000–₱13,000",
    travelType: ["Beach", "Leisure"],
  },
  {
    id: "VS-18",
    region: "Visayas",
    destination: "Siquijor",
    set: "A",
    duration: "1 Day",
    packageName: "Siquijor Day Tour Set A",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/Cabugahay Falls.jpg", "/visayas/spots/San Juan Beach.jpg"],
    foodImage: "/visayas/dining/hut food.jpg",
    inclusions: ["Heritage & waterfalls day tour"],
    expenses: { accommodation: 0, food: 600, activities: 800, misc: 200 },
    estimatedCost: "₱2,000–₱3,000",
    travelType: ["Nature", "Day Trip"],
  },
  {
    id: "VS-19",
    region: "Visayas",
    destination: "Siquijor",
    set: "B",
    duration: "1 Day",
    packageName: "Siquijor Island Leisure Set B",
    accommodation: "None",
    accommodationImage: "",
    spotImages: ["/visayas/spots/San Juan Beach.jpg", "/visayas/spots/Cabugahay Falls.jpg"],
    foodImage: "/visayas/dining/foodss.jpg",
    inclusions: ["Beach relaxation", "Seafood lunch optional"],
    expenses: { accommodation: 0, food: 800, activities: 1000, misc: 300 },
    estimatedCost: "₱3,000–₱4,500",
    travelType: ["Beach"],
  },
];

export default visayas;
